version: '3'

services:
  redis:
    image: redis:7.2.1-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - redis
